### ISSUE TITLE
Adding to whitelist causes crash

### ISSUE THREAD

**Issue by Enderbyte09** [Enderbyte-Programs/CraftServerSetup#35]
TYPE: <class 'UnboundLocalError'>                                                                                       MESSAGE: cannot access local variable 'pluid' where it is not associated with a value                                   Traceback (most recent call last):                                                                                        File "craftserversetup.py", line 3333, in main                                                                          File "craftserversetup.py", line 1296, in servermgrmenu                                                                 File "craftserversetup.py", line 2139, in manage_server                                                                 File "craftserversetup.py", line 656, in manage_whitelist                                                             UnboundLocalError: cannot access local variable 'pluid' where it is not associated with a value

**Comment by Enderbyte09** [comment]
Happens only when list is empty

**Comment by Enderbyte09** [comment]
Fix 1.38.1
